name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.5'

    - name: List file structure for debug
      run: ls

    - name: Build OrderService (skip tests)
      run: gradle -p Order_Service build -x test

    - name: Upload JAR Artifact for Docker
      uses: actions/upload-artifact@v4
      with:
        name: orderservice-jar
        path: Order_Service/build/libs/*.jar

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.5'

    - name: Build OrderService
      run: gradle -p Order_Service build

    - name: Run OrderService Tests
      run: gradle -p Order_Service test

  dockerhub-push:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Order_Service with Gradle
      run: gradle -p Order_Service build

    - name: Copy JAR to Docker context
      run: cp Order_Service/build/libs/*.jar Order_Service/    

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Extract Git SHA
      id: vars
      run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build and Push OrderService Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./Order_Service
        push: true
        tags: |
          refl21/orderservicerepo:${{ env.GIT_SHA }}
          refl21/orderservicerepo:latest
